export class RepositoryConsts {

  public static DATABASE_CONNECTION_PARACHAIN_BALANCE: string =
    'DATABASE_CONNECTION_PARACHAIN_BALANCE';

  public static PARACHAIN_BALANCE_ACCOUNT_REPOSITORY: string =
    'PARACHAIN_BALANCE_ACCOUNT_REPOSITORY';
  public static PARACHAIN_BALANCE_ACCOUNT_SNAPSHOTS_REPOSITORY: string =
    'PARACHAIN_BALANCE_ACCOUNT_SNAPSHOTS_REPOSITORY';
  public static PARACHAIN_BALANCE_BALANCE_SETS_REPOSITORY: string =
    'PARACHAIN_BALANCE_BALANCE_SETS_REPOSITORY';
  public static PARACHAIN_BALANCE_DEPOSITS_REPOSITORY: string =
    'PARACHAIN_BALANCE_DEPOSITS_REPOSITORY';
  public static PARACHAIN_BALANCE_ENDOWEDS_REPOSITORY: string =
    'PARACHAIN_BALANCE_ENDOWEDS_REPOSITORY';
  public static PARACHAIN_BALANCE_RESERVEDS_REPOSITORY: string =
    'PARACHAIN_BALANCE_RESERVEDS_REPOSITORY';
  public static PARACHAIN_BALANCE_RESERVREPATRIATEDS_REPOSITORY: string =
    'PARACHAIN_BALANCE_RESERVREPATRIATEDS_REPOSITORY';
  public static PARACHAIN_BALANCE_SLASH_REPOSITORY: string =
    'PARACHAIN_BALANCE_SLASH_REPOSITORY';
  public static PARACHAIN_BALANCE_TRANSFERS_REPOSITORY: string =
    'PARACHAIN_BALANCE_TRANSFERS_REPOSITORY';
  public static PARACHAIN_BALANCE_UNRESERVEDS_REPOSITORY: string =
    'PARACHAIN_BALANCE_UNRESERVEDS_REPOSITORY';
  public static PARACHAIN_BALANCE_WITHDRAWS_REPOSITORY: string =
    'PARACHAIN_BALANCE_WITHDRAWS_REPOSITORY';
  public static PARACHAIN_BALANCE_ACCOUNTS_LATEST_SYNC_BLOCK_REPOSITORY: string =
    'PARACHAIN_BALANCE_ACCOUNTS_LATEST_SYNC_BLOCK_REPOSITORY';

}
